Resolved unauthorised access issue for skopeo-copy
openshift-pipelines/task-containers pull request #99
Opened 2024-08-29 05:23 UTC by Senjuti256

With reference to the JIRA issue https://issues.redhat.com/browse/SRVKP-5894, where skopeo-copy was failing with the error "unauthorized: access to the requested resource is not authorized while writing manifest".
The issue is caused by the skopeo task attempting to create a directory at the root of the container's filesystem (/.docker), which is typically restricted due to permission issues hence the destination for the credentials (.docker directory) is set to a writable path within the container's filesystem, such as a directory within the /tekton/home.

Signed off by @Senjuti256 [sde@redhat.com](mailto:sde@redhat.com)

2024-08-29 06:37 UTC, savitaashture commented
/test osp-114-ocp-415-e2e

2024-08-29 06:57 UTC, Senjuti256 commented
/retest-required

2024-08-29 12:07 UTC, vdemeester requested changes
So `/tekton/home` is a ["tekton reserved" directory](https://tekton.dev/docs/pipelines/tasks/#reserved-directories) and thus, we shouldn't necessarily rely on it, nor create it (as a volume, …).

The error in the SRVKP issue is because we do not set the `HOME` environment variable and thus it because `/`. We should make sure we set the `HOME` environment variable in our `Task` and in a folder that will be writable by the process. *But* we don't need a volume, nor using `/tekton/home` 👼🏼

2024-08-30 04:12 UTC, Senjuti256 commented
Addressed your changes @vdemeester

2024-08-30 06:06 UTC, Senjuti256 commented
/retest

2024-08-30 06:40 UTC, Senjuti256 commented
/test osp-115-ocp-415-e2e

2024-08-30 12:28 UTC, merged